exports.messageList = {
  M001: "User created successfully!",
  M002: "User with provided email already exists!",
  M003: "Error while creating user!",
  M004: "Task added successfully!",
  M005: "Task updated successfully!",
  M006: "Task deleted successfully!",
  M007: "User not found!",
  M008: "Task not found!",
  M009: "Tasks list fetched successfully!",
  M010: "Sub tasks created successfully!",
  M011: "Sub tasks updated successfully!",
  M012: "Sub tasks deleted successfully!",
  M013: "Sub task not found!",
  M014: "Sub tasks list fetched successfully!",
};
